// Code generated by goctl. DO NOT EDIT.
package types

type ProductCreateRequest struct {
	ProductName  string  `json:"product_name"`
	ProductCode  string  `json:"product_code"`
	ProductPrice float64 `json:"product_price"`
	ProductDesc  string  `json:"product_desc"`
}

type ProductCreateResponse struct {
	ProductName string `json:"product_name"`
}
