// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	product "github.com/HsiaoCz/zero-clone/product_service/internal/handler/product"
	"github.com/HsiaoCz/zero-clone/product_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: product.ProductCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
