// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	dart "github.com/HsiaoCz/zero-clone/product_service/internal/handler/dart"
	producer "github.com/HsiaoCz/zero-clone/product_service/internal/handler/producer"
	product "github.com/HsiaoCz/zero-clone/product_service/internal/handler/product"
	"github.com/HsiaoCz/zero-clone/product_service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: dart.DartCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/dart"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: producer.ProducerCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/producer"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: product.ProductCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/product"),
	)
}
